CREATE DATABASE MYTRANSPORT;
GO


CREATE TABLE USUARIO(
NIF INT,
SEXO  VARCHAR(1),
Nome	VARCHAR(15),
Data_Nasc	DATE,

PRIMARY KEY(NIF),

);
GO

CREATE TABLE CONTA(
ID_Conta  INT,
DATA	DATE,
NIF_Usuario INT

PRIMARY KEY(ID_Conta),
FOREIGN KEY(NIF_Usuario) REFERENCES USUARIO(NIF)
);
GO

CREATE TABLE VEICULO(
NOME	VARCHAR(15),
KM		REAL,
Matricula  INT,

PRIMARY KEY(Matricula)
);
GO

CREATE TABLE SCOOTER(
NOME	VARCHAR(15),
KM		REAL,
Matricula_Veiculo  INT,
CC INT,
Cor VARCHAR(20)

PRIMARY KEY(Matricula_Veiculo)
FOREIGN KEY(Matricula_Veiculo) REFERENCES VEICULO(Matricula)
);
GO

CREATE TABLE BIKE(
NOME	VARCHAR(15),
KM		REAL,
Matricula_Veiculo  INT,
Modelo INT,
Tipo INT

PRIMARY KEY(Matricula_Veiculo)
FOREIGN KEY(Matricula_Veiculo) REFERENCES VEICULO(Matricula)
);
GO

CREATE TABLE PATINETE(
NOME	VARCHAR(15),
KM		REAL,
Matricula_Veiculo  INT,
Fabricante VARCHAR(15),
Carga INT

PRIMARY KEY(Matricula_Veiculo)
FOREIGN KEY(Matricula_Veiculo) REFERENCES VEICULO(Matricula)
);
GO
