SELECT dbo.USUARIO.Nome, dbo.CONTA.DATA, dbo.VEICULO.NOME AS Expr1, dbo.SUBSCRICOES.DATA_INICIO, dbo.SUBSCRICOES.DATA_FIM, dbo.POSSUI.MATRICULA_VEICULO
FROM     dbo.POSSUI INNER JOIN
                  dbo.VEICULO ON dbo.POSSUI.MATRICULA_VEICULO = dbo.VEICULO.Matricula INNER JOIN
                  dbo.SUBSCRICOES ON dbo.VEICULO.Matricula = dbo.SUBSCRICOES.MATRICULA_VEICULO INNER JOIN
                  dbo.CONTA ON dbo.POSSUI.ID_CONTA = dbo.CONTA.ID_Conta AND dbo.SUBSCRICOES.ID_CONTA = dbo.CONTA.ID_Conta INNER JOIN
                  dbo.USUARIO ON dbo.CONTA.NIF_Usuario = dbo.USUARIO.NIF